### ISSUE TITLE
您好，@leetking,我对您这个项目比较感兴趣，请问您能提供关于这个项目的思路以及使用方法的readme吗？谢谢

### ISSUE THREAD

**Issue by ricardo-kcc** [leetking/leesym#1]

**Comment by leetking** [comment]
这个思路比较简单，主要参考 Intriguer 的依赖树来的，我再其基础上使用依赖图和操作数识别来搞的。其中hash之类的识别没有实现，毕业后没有继续搞这个方向了

**Comment by leetking** [comment]
使用方法：直接调用 leesym.py 即可，他会提示如何使用

**Comment by ricardo-kcc** [comment]
好的，谢谢。请问您觉得 Intriguer 还有较大的优化空间吗？

**Comment by leetking** [comment]
Intriguer 的思考方向还是有用的，二进制层面的符号执行，这个角度出发可以研究研究。优化的话还是有的，主要是指令关系的有效性，也可以结合 WEIZZ 的思想引入结构化编译试试。我当时的思路是这样的。

**Comment by ricardo-kcc** [comment]
请问方便加您qq吗？

**Comment by leetking** [comment]
li_tking at 163 dot com
你邮箱联系吧，不方便贴qq
